package com.example.demo.entity;

import lombok.*;
import jakarta.persistence.*;
import java.time.Instant;

/**
 * Represents actual power demand measured for a zone at a given time.
 * This class uses Lombok to generate boilerplate code like getters and setters.
 */
@Entity
@Table(name = "demand_readings")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DemandReading {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Many readings can belong to one electrical zone.
     * Maps to the 'zone_id' column in the database.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "zone_id", nullable = false)
    private Zone zone;

    /**
     * The actual power demand in Megawatts (MW).
     * Must be >= 0 according to business rules.
     */
    private Double demandMW;

    /**
     * The timestamp when the reading was recorded.
     * Must not be in the future.
     */
    private Instant recordedAt;

    // The getters and setters are automatically generated by @Data during compilation.
    // Example: getId(), setId(Long id), getDemandMW(), setDemandMW(Double value), etc.
}